# Site
title: 郭海林的博客
subtitle: ''
description: 'yibu,郭海林,博客,JS,webpack,前端,Java'
keywords:
author: yibu
language: zh-CN
timezone: ''

navbar:
  blog_title: 郭海林的博客

# 首页大图中的标题文字
index:
  slogan:
    enable: false
    text: 不断学习，不断成长


#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  # 页脚第一行文字的 HTML，建议保留 Fluid 的链接，用于向更多人推广本主题
  # HTML of the first line of the footer, it is recommended to keep the Fluid link to promote this theme to more people
  # content: '
  #   <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
  #   <i class="iconfont icon-love"></i>
  #   <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
  # '
  content:

  # 展示网站的 PV、UV 统计数
  # Display website PV and UV statistics
  statistics:
    enable: true
    # 统计数据来源，使用 leancloud 需要设置 `web_analytics: leancloud` 中的参数；使用 busuanzi 不需要额外设置，但是有时不稳定，另外本地运行时 busuanzi 显示统计数据很大属于正常现象，部署后会正常
    # Data source. If use leancloud, you need to set the parameter in `web_analytics: leancloud`
    # Options: busuanzi | leancloud
    source: "busuanzi"

  # 国内大陆服务器的备案信息
  # For Chinese mainland website policy, other areas keep disable
  beian:
    enable: true
    # ICP证号
    icp_text: 蜀ICP备2020031778号
    # 公安备案号，不填则只显示ICP
    police_text: 
    # 公安备案的编号，用于URL跳转查询
    police_code: 
    # 公安备案的图片. 为空时不显示备案图片
    police_icon: 